# -*- coding: utf-8 -*-
"""model_deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9nUusPdL-AhrZuxL9Sp13mGT8B4CMRs
"""

import duckdb
import os
import glob
import pandas as pd
import numpy as np

import shutil
import json


def show_model_list():
    dirname = os.path.dirname(__file__)
    models_path = os.path.join(dirname, '../storage/models')
    models = os.listdir(models_path)
    for idx, model in enumerate(models):
        model_path = os.path.join(models_path, model)
        with open(os.path.join(model_path, 'metadata.json'), 'r') as fp:
            model_metadata = json.load(fp)

        print(f'MODEL {idx} - {model}')
        print(model_metadata)
        which_model = input("Please, select a model (number) to deploy or quit: ")
        return which_model


def deploy_model():
    dirname = os.path.dirname(__file__)
    models_path = os.path.join(dirname, '../storage/models')
    models = os.listdir(models_path)
    which_model = show_model_list()
    deployment_model_path = os.path.join(dirname, '../../deployment/model')

    model_path = os.path.join(models_path, models[int(which_model)])
    if os.path.exists(deployment_model_path):
        shutil.rmtree(deployment_model_path)
    shutil.copytree(model_path, deployment_model_path)