# -*- coding: utf-8 -*-
"""data_discovery.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17EheKO6Mx-rJAFujkCJjjTSNzvQJeOX5
"""


import pandas as pd
import numpy
import os
import wbgapi as wb

currentdirectory = os.path.dirname(__file__)

def list_topics():
    print(wb.topic.info())


def list_sources():
    print('List of sources: ')
    df = wb.source.Series().to_frame()
    df['code'] = df.index
    df = df.reset_index(drop=True)
    print(df.to_string())


def show_indicators_of_topic(selected_topic):
    print(wb.series.info(wb.topic.members(selected_topic)))


def show_indicators_of_source(source_code):
    print(wb.series.info(db=source_code))




# Execute notebook


def executeDataDiscovery():
    list_sources()

    selected_source = input("Select a source: ")

    df = wb.source.Series().to_frame()
    df['code'] = df.index
    df.reset_index(drop=True)
    source_name = str(df.iloc[int(selected_source), 0])
    source_code = int(df.iloc[int(selected_source), 1])
    print(source_name)

    show_indicators_of_source(source_code)

    selected_indicators = input('Write the indicators codes separated by spaces: ').split()

    selected_indicators = [str(indicator) for indicator in selected_indicators]

    data = wb.data.DataFrame(selected_indicators, time=range(1992, 2020, 4), db=source_code,
                             columns='series').reset_index()

    source = source_name.replace(" ", "_")

    filename = f'{currentdirectory}/temporal/ind_wbg_{source}/ind_wbg_{source}.csv'
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    print("")
    with open(filename, 'w', encoding='utf-8-sig') as f:
        data.to_csv(f, index=False)