# -*- coding: utf-8 -*-
"""formmated_infodb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yChcZP2-ou9Oo4C9GUHvLjwWOFBlvG7K
"""
import duckdb
import itertools
import pandas as pd
import os

""" 

"""# EXECUTION OF THE PROCESS"""

def get_field_sub(x): 
   return x.split('$')[0]

def describeTrustedDB():

  dirname = os.path.dirname(__file__)
  con = duckdb.connect(database=os.path.join(dirname, '../storage/trusted.duckdb'), read_only=True)

  tables = con.execute("SHOW TABLES").fetchall()
  tables = list([t for (t,) in tables])

  # sort by timestamp
  tables.sort() 

  mylist = sorted(tables, key=get_field_sub)
  data = dict((x.split('$')[0],list(y)) for x, y in itertools.groupby(tables, get_field_sub))

  for ds in data:
    df = con.execute(f'SELECT * FROM {ds}').df()
    print(f'\n\n\n ======================== {ds} ========================\n\n')
    print(df.info())

  con.close()