# -*- coding: utf-8 -*-
"""formatted.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mXZhUtnWWkPRCRS3P_QfbloQqsvvB3Re
"""

#!pip install duckdb

import duckdb
import os
import glob
import pandas as pd
import numpy as np

#dirname = os.path.dirname(__file__)



"""# EXECUTION OF THE ZONE"""
 


def executeformatted():
  dirname = os.path.dirname(__file__)
  
  # create a duckdb database for the formatted zone
  con = duckdb.connect(database= os.path.join(dirname, '../storage/formatted.duckdb'), read_only=False)

  # get parent dir
  pardir = os.path.join(dirname, "../../")

  
  dir = pardir + 'landing/persistent/'

  # enter persistent dir
  os.chdir(dir)

  datasources = [name for name in os.listdir(".") if os.path.isdir(name)]

  # dictionary that contains all the table dataframes
  dictdf = {}

  # create a table for each datafile in each datasource
  for ds in datasources:
    os.chdir(dir + ds)
    files = glob.glob('*.{}'.format('csv'))
    for f in files:
      # omit '.csv'
      fname = f[:-4]
      con.execute(f'DROP TABLE IF EXISTS {fname}')
      con.execute(f"CREATE TABLE IF NOT EXISTS {fname} AS SELECT * FROM read_csv_auto('{dir}{ds}/{f}');")
      dictdf[fname] = con.execute(f"SELECT * FROM {fname}").df()

  #close connection
  con.close()