# -*- coding: utf-8 -*-
"""profiling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jffQ6GJTlKAEqEUrjRuHtNDPJZKAtARL
"""

# !pip install duckdb
import duckdb
import os
from pandas_profiling import ProfileReport
# ! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

# from google.colab import drive
# drive.mount('/content/drive')

# con = duckdb.connect(database='/content/drive/MyDrive/projecteADSDB/trusted/trusted.duckdb', read_only=True)

# tables = con.execute("SHOW TABLES").fetchall()
# tables = list([t for (t,) in tables])

# tables

# """### Profiling"""

# # import os
# # os._exit(00)

# import pandas as pd
# import numpy as np

# from pandas_profiling import ProfileReport

# for ds in tables:
#   df = con.execute(f'SELECT * FROM {ds}').df()
#   profile = ProfileReport(df, title=ds, html={'style' : {'full_width':True}})
#   profile.to_notebook_iframe()

# con.close()

"""# EXECUTION OF THE PROCESS"""

def execute_profiling():

  dirname = os.path.dirname(__file__)

  # connect to trusted database
  con = duckdb.connect(database=os.path.join(dirname, 'trusted.duckdb'), read_only=True)

  # obtain table names
  tables = con.execute("SHOW TABLES").fetchall()
  tables = list([t for (t,) in tables])

  #profile tables
  for ds in tables:
    df = con.execute(f'SELECT * FROM {ds}').df()
    profile = ProfileReport(df, title=ds, html={'style' : {'full_width':True}})
    profile.to_file(os.path.join(dirname, f'{ds}_report.html'))

  #close connection
  con.close()